(function(){'use strict';
const PUZZLE=[0, 0, 3, 0, 8, 1, 7, 2, 5, 0, 0, 4, 5, 9, 0, 0, 0, 8, 0, 7, 0, 2, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 9, 0, 0, 4, 1, 0, 0, 0, 5, 7, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 9, 0, 0, 0, 1, 6, 4, 0, 0, 4, 3, 6, 9, 7, 0, 1, 0, 0];
const SOLUTION=[6, 9, 3, 4, 8, 1, 7, 2, 5, 1, 2, 4, 5, 9, 7, 3, 6, 8, 5, 7, 8, 2, 6, 3, 9, 4, 1, 2, 5, 7, 1, 3, 4, 8, 9, 6, 8, 4, 1, 6, 2, 9, 5, 7, 3, 3, 6, 9, 7, 5, 8, 2, 1, 4, 7, 1, 5, 8, 4, 2, 6, 3, 9, 9, 8, 2, 3, 1, 6, 4, 5, 7, 4, 3, 6, 9, 7, 5, 1, 8, 2];
const gridEl=document.getElementById('sudoku-grid');const statusEl=document.getElementById('status');const keypadEl=document.getElementById('keypad');const values=PUZZLE.slice(),undoStack=[];let selected=PUZZLE.findIndex(v=>v===0);if(selected<0)selected=0;
const row=i=>Math.floor(i/9),col=i=>i%9,box=i=>Math.floor(row(i)/3)*3+Math.floor(col(i)/3);const current=i=>values[i]||0;const setStatus=(t,cls='')=>{statusEl.textContent=t;statusEl.className='status'+(cls?' '+cls:'');};const isComplete=()=>values.every(v=>v>=1&&v<=9);const isCorrect=()=>values.every((v,i)=>v===SOLUTION[i]);
function updateKeypad(){const counts=Array(10).fill(0);values.forEach(v=>{if(v>=1&&v<=9)counts[v]++;});keypadEl.querySelectorAll('button[data-number]').forEach(btn=>{const n=Number(btn.dataset.number);if(counts[n]>=9){btn.textContent=' ';btn.disabled=true;btn.classList.add('hidden-digit');}else{btn.textContent=String(n);btn.disabled=false;btn.classList.remove('hidden-digit');}});}
function build(){gridEl.innerHTML='';for(let i=0;i<81;i++){const b=document.createElement('button');b.type='button';b.className='cell';if(PUZZLE[i])b.classList.add('given');if(col(i)===2||col(i)===5)b.classList.add('box-right');if(row(i)===2||row(i)===5)b.classList.add('box-bottom');if(col(i)===8)b.classList.add('last-col');if(row(i)===8)b.classList.add('last-row');b.addEventListener('click',()=>{selected=i;render();});gridEl.appendChild(b);}render();}
function clearWrongMarks(){gridEl.querySelectorAll('.wrong').forEach(el=>el.classList.remove('wrong'));}
function maybeCelebrateAfterEntry(){if(isComplete()&&isCorrect()){setStatus('Congratulations! You solved Symmetrical Puzzle #006 correctly. 🎉','success');return true;}return false;}
function render(){updateKeypad();for(let i=0;i<81;i++){const b=gridEl.children[i],v=current(i);b.textContent=v?String(v):'';b.classList.remove('selected','peer','same-number');}if(selected>=0){const sv=current(selected),sr=row(selected),sc=col(selected),sb=box(selected);gridEl.children[selected].classList.add('selected');for(let i=0;i<81;i++)if(i!==selected){if(row(i)===sr||col(i)===sc||box(i)===sb)gridEl.children[i].classList.add('peer');if(sv&&current(i)===sv)gridEl.children[i].classList.add('same-number');}if(!(isComplete()&&isCorrect())){if(sv)setStatus('Digit '+sv+' selected. Matching digits are highlighted.');else setStatus('Empty cell selected. Row, column, and 3×3 box are highlighted.');}}}
function enter(n){if(PUZZLE[selected]){setStatus('Original clue cells cannot be changed.');render();return;}undoStack.push([selected,values[selected]]);values[selected]=Number(n);clearWrongMarks();render();if(!maybeCelebrateAfterEntry())setStatus('Number entered. Continue solving, or press Check when ready.');}
document.getElementById('erase-btn').onclick=()=>{if(PUZZLE[selected]){setStatus('Original clue cells cannot be erased.');return;}undoStack.push([selected,values[selected]]);values[selected]=0;clearWrongMarks();render();setStatus('Cell cleared.');};
document.getElementById('undo-btn').onclick=()=>{const x=undoStack.pop();if(x){values[x[0]]=x[1];selected=x[0];clearWrongMarks();render();setStatus('Last move undone.');}else setStatus('Nothing to undo.');};
document.getElementById('check-btn').onclick=()=>{const wrong=[];for(let i=0;i<81;i++)if(values[i]&&values[i]!==SOLUTION[i])wrong.push(i);clearWrongMarks();if(wrong.length){wrong.forEach(i=>gridEl.children[i].classList.add('wrong'));setStatus(String(wrong.length)+' incorrect entr'+(wrong.length===1?'y':'ies')+'. Highlighted cells can be corrected.','error');return;}if(isComplete()&&isCorrect()){setStatus('Congratulations! You solved Symmetrical Puzzle #006 correctly. 🎉','success');return;}setStatus('Everything entered so far is correct. Keep going!');};
document.getElementById('reset-btn').onclick=()=>{if(confirm('Clear all your entries and restart Puzzle #006?')){for(let i=0;i<81;i++)values[i]=PUZZLE[i];undoStack.length=0;selected=PUZZLE.findIndex(v=>v===0);if(selected<0)selected=0;clearWrongMarks();render();setStatus('Puzzle reset. Tap or click any cell to begin.');}};
keypadEl.addEventListener('click',e=>{const b=e.target.closest('button[data-number]');if(b&&!b.disabled)enter(b.dataset.number);});document.addEventListener('keydown',e=>{if(/^[1-9]$/.test(e.key)){const btn=keypadEl.querySelector('button[data-number=+e.key+]');if(btn&&!btn.disabled){e.preventDefault();enter(e.key);}}});build();})();